# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Herokuapp project

on:
  push:
    branches: [ "main" ]

permissions:
      contents: write
      pages: write
      id-token: write
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      CI: "true"
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pip'
        
    - name: Setup Chrome Browser
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable
        
    - name: Display Chrome Version
      run: |
        google-chrome --version
        which google-chrome
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest --alluredir=./reports/allure-results \
               --clean-alluredir \
               -v \
               --tb=short \
               --browser=chrome \
               --headless
      continue-on-error: true 
      
    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: ./reports/allure-results
        allure_history: ./reports/allure-history
        keep_reports: 20
    
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./reports/allure-history
